name: Build and Push Docker Image
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
permissions:
  contents: read
  id-token: write
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4    
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}        
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-east1-docker.pkg.dev --quiet
      - name: Install SOPS
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/getsops/sops/releases/download/v3.8.1/sops_3.8.1_amd64.deb
          sudo dpkg -i sops_3.8.1_amd64.deb
        
      - name: Decrypt secrets
        run: sops -d secrets/secrets.enc.yaml > .env
      - name: Build Docker image
        run: docker build -f Dockerfile -t us-east1-docker.pkg.dev/mockmentor-460805/mockmentor-python-server-dev/mockmentor-python-server-dev:latest .
      - name: Push Docker Images
        run: |
          docker push us-east1-docker.pkg.dev/mockmentor-460805/mockmentor-python-server-dev/mockmentor-python-server-dev:latest
          docker tag us-east1-docker.pkg.dev/mockmentor-460805/mockmentor-python-server-dev/mockmentor-python-server-dev:latest us-east1-docker.pkg.dev/mockmentor-460805/mockmentor-python-server-dev/mockmentor-python-server-dev:${{ github.sha }}
          docker push us-east1-docker.pkg.dev/mockmentor-460805/mockmentor-python-server-dev/mockmentor-python-server-dev:${{ github.sha }}
      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: 'mockmentor-ai-service-dev'
          image: 'us-east1-docker.pkg.dev/mockmentor-460805/mockmentor-ai-service-dev/mockmentor-ai-service-dev:latest'
          region: 'us-east1'
